### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by lukasbystricky** [bobrk/d-h-lawrence_lady-chatterleys-lover#1]
- [x] Update your toolset and run modernize-spelling.  re-entering -> reentering should be accepted.
- [x] Copy over the new core.css and se.css files
- [x] chapter-17, line 92: modernize-spelling changed for ever to forever. I think this should be reverted.
- [x] long description: 21st century -> twentieth century
- [x] For the LoC identifiers we typically go with the form like https://id.loc.gov/authorities/names/n79018450.htm
- [x] I'm not sure I understand 43edec2. What's wrong with replacing the double quotes with single quotes?

**Comment by bobrk** [comment]
Hmm. First item. I did the pipx upgrade to standard ebooks and I was on the lated version, 2.6.4. Running modernize spelling changed two other things, erroneously, but not reentering. I will find it and fix it manually.

la[---]me-do-la  (took out a dash that should be there)

 <p>Connie guessed, however, that her father had said something, and that something was in Clifford’s mind. She knew that he didn’t mind whether she were <i xml:lang="fr">demi-vierge</i> or <i xml:lang="fr">demi[---]monde</i>, so long as he didn’t absolutely know, and wasn’t made to see. What the eye doesn’t see and the mind doesn’t know, doesn’t exist.</p>
(stylistically left the dash in to match "Demi-vierge" which is not in the dictionary. I had sent an email asking about this one to the list, about whether I should just leave the French tag on demimonde to match the other word, and decided to leave the dash in as well.

**Comment by bobrk** [comment]
item 2: I copied the core and se.css files over from /Users/bob/.local/pipx/venvs/standardebooks/lib/python3.9/site-packages/se/data/templates/ and they were identical, according to git.

**Comment by bobrk** [comment]
item 5: link was 404. I used the same format as the prefilled author LoC, let me know what I should do.

**Comment by bobrk** [comment]
item 6: I had thought about using single quotes but it was my impression that these were emphasized words and went with that. Happy to change it to single quotes.

**Comment by lukasbystricky** [comment]
> Hmm. First item. I did the pipx upgrade to standard ebooks and I was on the lated version, 2.6.4. Running modernize spelling changed two other things, erroneously, but not reentering. I will find it and fix it manually.
> 
> la[---]me-do-la (took out a dash that should be there)
> 
> Connie guessed, however, that her father had said something, and that something was in Clifford’s mind. She knew that he didn’t mind whether she were demi-vierge or demi[---]monde, so long as he didn’t absolutely know, and wasn’t made to see. What the eye doesn’t see and the mind doesn’t know, doesn’t exist.
> 
> (stylistically left the dash in to match "Demi-vierge" which is not in the dictionary. I had sent an email asking about this one to the list, about whether I should just leave the French tag on demimonde to match the other word, and decided to leave the dash in as well.

Yes, I think re-entering to reentering is the only change that should be made. The others can be left as is.



> item 2: I copied the core and se.css files over from /Users/bob/.local/pipx/venvs/standardebooks/lib/python3.9/site-packages/se/data/templates/ and they were identical, according to git.

I'm on the development branch running 2.7.3, so maybe that's ok. You can leave the CSS files and Alex can update them if need be.



> item 5: link was 404. I used the same format as the prefilled author LoC, let me know what I should do.

Somehow the last "l" got deleted, it should be [https://id.loc.gov/authorities/names/n79018450.html](https://id.loc.gov/authorities/names/n79018450.html). In the initial commit It doesn't look like it filled anything in for the author LOC entry, so I think that should be replaced. 



> item 6: I had thought about using single quotes but it was my impression that these were emphasized words and went with that. Happy to change it to single quotes.

It is sort of emphasis, but since it's quoted in the scans I'd leave them as quotes.

**Comment by bobrk** [comment]
Ah, I think you are correct about the LoC, I must have filled that in wrong. Thanks for that.

**Comment by bobrk** [comment]
Ok, I think I got everything.

**Comment by bobrk** [comment]
Ok, I think I got everything.
